### ISSUE TITLE
Variational encoding

### ISSUE THREAD

**Issue by marshvee** [mkusner/grammarVAE#13]
How can I remove the "variational" part of the autoencoder, to get a plain autoencoder? What parameters or sections of the code control this?

**Comment by mkusner** [comment]
Hey Marianars013. To make it a plain autoencoder you'll need to make the encoder deterministic and remvove the KL term in the loss. I think these changes should do it (I'll use model_zinc as an example but the same changes apply to the rest of the code):
- Change this: https://github.com/mkusner/grammarVAE/blob/master/models/model_zinc.py#L124  to just: return xent_loss
- Change this: https://github.com/mkusner/grammarVAE/blob/master/models/model_zinc.py#L126 to just: return z_mean
