### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by agane** [mkusner/grammarVAE#17]
What's the expected (approx.) training time for symbolic regression/zinc with the hyper-parameters in the paper (i.e. 100 epochs)?

**Comment by mkusner** [comment]
Ah I'm sorry I don't have the times with me at the moment but I would expect anywhere from 15-30 hours.

**Comment by agane** [comment]
Thanks! Is this for symbolic regression or zinc (or both)?

**Comment by mkusner** [comment]
Ah sorry that's for zinc! The symbolic regression should take much less time, I believe a few hours.

**Comment by agane** [comment]
Perfect, thanks!
