### ISSUE TITLE
Latent Space Gradient for Equations Data

### ISSUE THREAD

**Issue by agane** [mkusner/grammarVAE#20]
Hi! I used PCA to plot the grammarVAE latent space into 2 dimensions and colored them by the symbolic regression score (similar to the LogP plot you have in your paper). However, the colors are quite mixed (I don't see the score gradient I expected). (Otherwise the model performs well.)

Have you encountered this issue with equations? Or did you only attempt plotting the LogP?

Thanks in advance for the information!

**Comment by mkusner** [comment]
Ah this is good to know. We only tried plotting the LogP. My guess here is that our architecture/optimization parameters are suboptimal for the symbolic equation setting. We didn't try many settings. I think a small amount of tuning would give you better results.
