### ISSUE TITLE
Pytorch implementation of Bayesian Optimization

### ISSUE THREAD

**Issue by Bibyutatsu** [mkusner/grammarVAE#28]
Hi,
I have tried the Bayesian Optimization which is coded in Theano. It was working great (Though it was taking a lot of time for training and sampling), but I wanted to port the whole pipeline in Pytorch.

So can you mention some sources where I can find this implementation in Pytorch.

**Comment by mkusner** [comment]
Do you mean Bayesian optimization or the GrammarVAE? Here are both:

BO: https://github.com/pytorch/botorch

GrammarVAE:
- https://github.com/episodeyang/grammar_variational_autoencoder
- https://github.com/ZmeiGorynych/grammarVAE_pytorch
