### ISSUE TITLE
TypeError: object of type 'filter' has no len()

### ISSUE THREAD

**Issue by cahsmann** [mkusner/grammarVAE#32]
I am getting this error at line 12 in molecule_vae.py

**Comment by nzarnaghi** [comment]
Hi,

Python 2.7 is getting deprecated. That is why it shows this error. I changed that line to "assert len(list(long_tokens)) == len(list(replacements))" and it worked. I put some upgraded codes to Python3 here:

https://github.com/nzarnaghi/GrammarVAE_py3

**Comment by mkusner** [comment]
Thanks for the upgrade! I recommend using this above code or the pytorch grammar vae code here when using python 3!: https://github.com/geyang/grammar_variational_autoencoder
