### ISSUE TITLE
binary accuracy

### ISSUE THREAD

**Issue by Yuanpengli** [mkusner/grammarVAE#5]
Hi Kusner: 
First of all, thank for your contributions. I just want know how much is binary_accuracy of grammar_vae when we train molecular (smiles) model.
I think it is great progress comparing with the CVAE.
Best wshes.
Yuanpeng Li

**Comment by jaredwillard12** [comment]
Hey @Yuanpengli, from what I've gathered, the model that they're using is using categorical accuracy, not binary accuracy. 

Example:   (True) "The dog ran" ******* (Encoded-Then-Decoded) "The duck ran" --> 66% accuracy

**Comment by Yuanpengli** [comment]
@jaredwillard12 Thank you. It is categorical accuracy. 
I got most 85% categorical accuracy. But the decoded smiles is so different with the origin smiles. I don't know why.
Thank you very much.

**Comment by jaredwillard12** [comment]
@Yuanpengli How different are the smiles? Could you post an example of some of your output?

**Comment by mkusner** [comment]
I also should point out that decoding is stochastic so it may be that you sometimes get different SMILES strings depending on the sample you draw from the decoder.

**Comment by Yuanpengli** [comment]
@jaredwillard12 The original smiles is 'c1ccccc1'. $z_mean_ + K.exp(z_log_var_ / 2) * epsilon$ I set epsilon is variable x is normal distribution N(0, 0.00001). I want to get the same smiles from output in net.
But I got smiles 'Fccccc'. I also deleted the random decoded part in following code
:np.argmax(np.random.gumbel(size=masked_output.shape) + np.log(masked_output), axis=-1)

**Comment by mkusner** [comment]
If you'd like the encoding/decoding to not be stochastic you can make the following changes and retrain:
- Change this: https://github.com/mkusner/grammarVAE/blob/master/models/model_zinc.py#L124  to just: return xent_loss
- Change this: https://github.com/mkusner/grammarVAE/blob/master/models/model_zinc.py#L126 to just: return z_mean

And then when you decode you can just use the mean!
